#ifndef _HTML_TEMPLATES_H_
#define _HTML_TEMPLATES_H_

#ifdef __cplusplus
extern "C" {
#endif

const char *html_template = 
"<!DOCTYPE html>\n"
"<html lang=\"ru\">\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"    <title>Статистика температуры</title>\n"
"    <style>\n"
"        * {margin: 0;padding: 0;box-sizing: border-box;}\n"
"        body {font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;background: #d5d5d5;padding: 20px;color: #333;}\n"
"        .container {max-width: 800px;margin: 0 auto;}\n"
"        section {background: white;padding: 10px 20px;}\n"
"        h1, h2, .subtitle, .description {text-align: center;}\n"
"        h1 { font-size: 2.5em; margin-bottom: 8px; }\n"
"        h2 {margin-bottom: 15px; font-size: 1.3em;}\n"
"        .subtitle {font-size: 1em; margin-bottom: 15px;}\n"
"        .description {color: #4a4a4a; max-width: 600px; margin: 0 auto; font-size: 0.9em;}\n"
"        .table-wrapper {overflow-x: auto;}\n"
"        table {width: 100%;border-collapse: collapse;font-size: 0.85em;}\n"
"        th, td {padding: 5px 8px;text-align: center;border-bottom: 1px solid #f0f0f0;}\n"
"        th {background: #8ecdd8;font-weight: 600;}\n"
"        td:first-child {text-align: left;font-weight: 600;}\n"
"        tr:last-child td {border-bottom: none;}\n"
"        .chart-section {text-align: center;}\n"
"        @media (max-width: 768px) {body { padding: 15px; }section { padding: 20px; }h1 { font-size: 2em; }}\n"
"    </style>\n"
"    <script></script>\n"
"</head>\n"
"<body>\n"
"    <div class=\"container\">\n"
"        <section>\n"
"            <h2>Статистика температуры</h2>\n"
"            <p class=\"subtitle\">Курсовая работа. Си базовый уровень. гр.Д01-134 Попов. В.Г</p>\n"
"            <p class=\"description\">\n"
"                Файл сгенерирован программой report.\n"
"            </p>\n"
"        </section>\n"
"        <section>\n"
"            <h2>Статистика за год:</h2>\n"
"            <div class=\"table-wrapper\">\n"
"                <table id=\"id_table_report\">\n"
"                    <thead>\n"
"                        <tr>\n"
"                            <th>Месяц</th>\n"
"                            <th>Средняя T°C</th>\n"
"                            <th>Мин. T°C</th>\n"
"                            <th>Макс. T°C</th>\n"
"                        </tr>\n"
"                    </thead>\n"
"                    <tbody>\n"
"                    </tbody>\n"
"                </table>\n"
"            </div>\n"
"           <section class=\"chart-section\">"
"              <h2>График температуры за год</h2>"
"              <canvas id=\"tempChart\" width=\"600\" height=\"300\"></canvas>"
"           </section>"
"    </div>\n"
"</body>\n";


const char *js_code = 
"function averageMonthlyTemperature(tarr, month) {\n"
"    if (!tarr || tarr.length === 0) return null;\n"
"    if (month < 1 || month > 12) return null;\n"
"    let sum = 0;\n"
"    let count = 0;\n"
"    for (let i = 0; i < tarr.length; i++) {\n"
"        if (tarr[i].m === month) {\n"
"            sum += tarr[i].t;\n"
"            count++;\n"
"        }\n"
"    }\n"
"    return parseInt(sum / count);\n"
"}\n"
"function minTemperatureCurrentMonth(tarr, month) {\n"
"    if (!tarr || tarr.length === 0) return null;\n"
"    if (month < 1 || month > 12) return null;\n"
"    let minTemp = Infinity;\n"
"    let found = false;\n"
"    for (let i = 0; i < tarr.length; i++) {\n"
"        if (tarr[i].m === month && tarr[i].t < minTemp) {\n"
"            minTemp = tarr[i].t;\n"
"            found = true;\n"
"        }\n"
"    }\n"
"    return found ? minTemp : null;\n"
"}\n"
"function maxTemperatureCurrentMonth(tarr, month) {\n"
"    if (!tarr || tarr.length === 0) return null;\n"
"    if (month < 1 || month > 12) return null;\n"
"    let maxTemp = -Infinity;\n"
"    let found = false;\n"
"    for (let i = 0; i < tarr.length; i++) {\n"
"        if (tarr[i].m === month && tarr[i].t > maxTemp) {\n"
"            maxTemp = tarr[i].t;\n"
"            found = true;\n"
"        }\n"
"    }\n"
"    return found ? maxTemp : null;\n"
"}\n"
"function averageAnnualTemperature(tarr) {\n"
"    if (!tarr || tarr.length === 0) return null;\n"
"    let sum = 0;\n"
"    for (let i = 0; i < tarr.length; i++) {\n"
"        sum += tarr[i].t;\n"
"    }\n"
"    return parseInt(sum / tarr.length);\n"
"}\n"
"function minimumTemperature(tarr) {\n"
"    if (!tarr || tarr.length === 0) return null;\n"
"    let minTemp = Infinity;\n"
"    for (let i = 0; i < tarr.length; i++) {\n"
"        if (tarr[i].t < minTemp) {minTemp = tarr[i].t;}\n"
"    }\n"
"    return minTemp;\n"
"}\n"
"function maximumTemperature(tarr) {\n"
"    if (!tarr || tarr.length === 0) return null;\n"
"    let maxTemp = -Infinity;\n"
"    for (let i = 0; i < tarr.length; i++) {\n"
"        if (tarr[i].t > maxTemp) {maxTemp = tarr[i].t;}\n"
"    }\n"
"    return maxTemp;\n"
"}\n"
"function calculateStatistics(tarr) {\n"
"    const stats = {\n"
"        months: [],\n"
"        avgYear: null,\n"
"        minTempYear: null,\n"
"        maxTempYear: null,\n"
"        error: 0\n"
"    };\n"
"    if (!tarr) {\n"
"        stats.error = 1;\n"
"        return stats;\n"
"    }\n"
"    if (tarr.length === 0) {\n"
"        stats.error = 2;\n"
"        return stats;\n"
"    }\n"
"    for (let i = 0; i < 12; i++) {\n"
"        const monthStats = {\n"
"            avgTemp: averageMonthlyTemperature(tarr, i + 1),\n"
"            maxTemp: maxTemperatureCurrentMonth(tarr, i + 1),\n"
"            minTemp: minTemperatureCurrentMonth(tarr, i + 1)\n"
"        };\n"
"        if (monthStats.avgTemp === null) {stats.error = 3;}\n"
"        stats.months.push(monthStats);\n"
"    }\n"
"    stats.avgYear = averageAnnualTemperature(tarr);\n"
"    stats.minTempYear = minimumTemperature(tarr);\n"
"    stats.maxTempYear = maximumTemperature(tarr);\n"
"    return stats;\n"
"}\n"
"function fillStatsTable(stats) {\n"
"    const MONTHS = [\"JAN\", \"FEB\", \"MAR\", \"APR\", \"MAY\", \"JUN\", \"JUL\", \"AUG\", \"SEP\", \"OCT\", \"NOV\", \"DEC\"];\n"
"    const tbody = document.querySelector('#id_table_report tbody');\n"
"    if (!tbody) return;\n"
"    let htmlContent = '';\n"
"    for (let i = 0; i < 12; i++) {\n"
"        const monthData = stats.months?.[i] || {};\n"
"        const avg = monthData.avgTemp ?? '-';\n"
"        const min = monthData.minTemp ?? '-';\n"
"        const max = monthData.maxTemp ?? '-';\n"
"        htmlContent += `<tr><td>${MONTHS[i]}</td><td>${avg}</td><td>${min}</td><td>${max}</td></tr>`;\n"
"    }\n"
"    const yearAvg = stats.avgYear ?? '-';\n"
"    const yearMin = stats.minTempYear ?? '-';\n"
"    const yearMax = stats.maxTempYear ?? '-';\n"
"    htmlContent += `<tr>\n"
"        <td><strong>YEAR TOTAL</strong></td>\n"
"        <td><strong>${yearAvg}</strong></td>\n"
"        <td><strong>${yearMin}</strong></td>\n"
"        <td><strong>${yearMax}</strong></td>\n"
"    </tr>`;\n"
"    tbody.innerHTML = htmlContent;\n"
"}\n"
"const stats = calculateStatistics(arrayTempStats);\n"
"fillStatsTable(stats);\n";


const char *js_drawChart = 
"function drawChart(stats) {\n"
"    const canvas = document.getElementById('tempChart');\n"
"    if (!canvas) return;\n"
"    const ctx = canvas.getContext('2d');\n"
"    const W = canvas.width;\n"
"    const H = canvas.height;\n"
"    const MONTHS = [\"JAN\", \"FEB\", \"MAR\", \"APR\", \"MAY\", \"JUN\", \"JUL\", \"AUG\", \"SEP\", \"OCT\", \"NOV\", \"DEC\"];\n"
"    const padding = { top: 30, right: 30, bottom: 40, left: 40 };\n"
"    const chartW = W - padding.left - padding.right;\n"
"    const chartH = H - padding.top - padding.bottom;\n"
"    const allTemps = stats.months.flatMap(m => [m.minTemp, m.maxTemp, m.avgTemp].filter(t => t !== null));\n"
"    const minT = Math.min(...allTemps) - 5;\n"
"    const maxT = Math.max(...allTemps) + 5;\n"
"    const rangeT = maxT - minT;\n"
"    ctx.fillStyle = '#fff';\n"
"    ctx.fillRect(0, 0, W, H);\n"
"    ctx.strokeStyle = '#ddd';\n"
"    ctx.lineWidth = 0.5;\n"
"    ctx.fillStyle = '#333';\n"
"    ctx.font = '10px Arial';\n"
"    ctx.textAlign = 'right';\n"
"    for (let t = Math.ceil(minT / 5) * 5; t <= maxT; t += 5) {\n"
"        const y = padding.top + chartH - ((t - minT) / rangeT) * chartH;\n"
"        ctx.beginPath();\n"
"        ctx.moveTo(padding.left, y);\n"
"        ctx.lineTo(W - padding.right, y);\n"
"        ctx.stroke();\n"
"        ctx.fillText(t + '\\u00b0', padding.left - 5, y + 3);\n"
"    }\n"
"    ctx.textAlign = 'center';\n"
"    const stepX = chartW / 11;\n"
"    for (let i = 0; i < 12; i++) {\n"
"        ctx.fillText(MONTHS[i], padding.left + i * stepX, H - padding.bottom + 15);\n"
"    }\n"
"    function drawLine(values, color, width, dash) {\n"
"        ctx.strokeStyle = color;\n"
"        ctx.lineWidth = width;\n"
"        ctx.setLineDash(dash || []);\n"
"        ctx.beginPath();\n"
"        let first = true;\n"
"        for (let i = 0; i < 12; i++) {\n"
"            if (values[i] === null) continue;\n"
"            const x = padding.left + i * stepX;\n"
"            const y = padding.top + chartH - ((values[i] - minT) / rangeT) * chartH;\n"
"            if (first) { ctx.moveTo(x, y); first = false; }\n"
"            else ctx.lineTo(x, y);\n"
"        }\n"
"        ctx.stroke();\n"
"        ctx.setLineDash([]);\n"
"    }\n"
"    function drawDots(values, color) {\n"
"        ctx.fillStyle = color;\n"
"        for (let i = 0; i < 12; i++) {\n"
"            if (values[i] === null) continue;\n"
"            const x = padding.left + i * stepX;\n"
"            const y = padding.top + chartH - ((values[i] - minT) / rangeT) * chartH;\n"
"            ctx.beginPath();\n"
"            ctx.arc(x, y, 3, 0, Math.PI * 2);\n"
"            ctx.fill();\n"
"        }\n"
"    }\n"
"    const avgValues = stats.months.map(m => m.avgTemp);\n"
"    const minValues = stats.months.map(m => m.minTemp);\n"
"    const maxValues = stats.months.map(m => m.maxTemp);\n"
"    drawLine(minValues, '#3498db', 1.5, [4, 3]);\n"
"    drawLine(maxValues, '#e74c3c', 1.5, [4, 3]);\n"
"    drawLine(avgValues, '#27ae60', 2.5);\n"
"    drawDots(avgValues, '#27ae60');\n"
"    drawDots(minValues, '#3498db');\n"
"    drawDots(maxValues, '#e74c3c');\n"
"    const legendX = W - padding.right - 100;\n"
"    const legendY = padding.top + 5;\n"
"    ctx.font = '11px Arial';\n"
"    ctx.textAlign = 'left';\n"
"    ctx.fillStyle = '#27ae60';\n"
"    ctx.fillRect(legendX, legendY, 15, 3);\n"
"    ctx.fillStyle = '#333';\n"
"    ctx.fillText('Средняя', legendX + 20, legendY + 5);\n"
"    ctx.fillStyle = '#3498db';\n"
"    ctx.setLineDash([4, 3]);\n"
"    ctx.strokeStyle = '#3498db';\n"
"    ctx.beginPath();\n"
"    ctx.moveTo(legendX, legendY + 16);\n"
"    ctx.lineTo(legendX + 15, legendY + 16);\n"
"    ctx.stroke();\n"
"    ctx.setLineDash([]);\n"
"    ctx.fillStyle = '#333';\n"
"    ctx.fillText('Минимальная', legendX + 20, legendY + 19);\n"
"    ctx.fillStyle = '#e74c3c';\n"
"    ctx.setLineDash([4, 3]);\n"
"    ctx.strokeStyle = '#e74c3c';\n"
"    ctx.beginPath();\n"
"    ctx.moveTo(legendX, legendY + 31);\n"
"    ctx.lineTo(legendX + 15, legendY + 31);\n"
"    ctx.stroke();\n"
"    ctx.setLineDash([]);\n"
"    ctx.fillStyle = '#333';\n"
"    ctx.fillText('Максимальная', legendX + 20, legendY + 34);}\n"
"drawChart(stats);\n";

#ifdef __cplusplus
}
#endif

#endif